"""Inference pipeline: chunk-execute-reobserve loop.

Loads the fine-tuned Qwen2.5-VL model (merged LoRA adapter), then runs the
following loop until completion or max_chunks is reached:

  1. Observe  -- convert current canvas ndarray to PIL image
  2. Predict  -- model generates a JSON 5-action chunk
  3. Execute  -- canvas executor applies all 5 actions sequentially
  4. Repeat   -- until all-noop chunk or max_chunks exceeded

Optionally uses temporal ensembling: execute only k < horizon actions before
re-observing, averaging overlapping predictions for smoother transitions.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

import os

import numpy as np
import torch
import yaml
from huggingface_hub import scan_cache_dir
from PIL import Image

os.environ.setdefault("UNSLOTH_COMPILE_DISABLE", "1")

from elysium.engine.canvas import execute_chunk
from elysium.schemas.actions import ActionChunk, parse_action

__all__ = ["Predictor", "run_inference"]

logger = logging.getLogger(__name__)


def _load_config(config_path: Path) -> dict[str, Any]:
    with config_path.open() as f:
        return yaml.safe_load(f)


def _image_to_float32(image: Image.Image) -> np.ndarray:
    """PIL RGB image -> float32 ndarray [0, 1]."""
    return np.array(image.convert("RGB"), dtype=np.float32) / 255.0


def _float32_to_pil(canvas: np.ndarray) -> Image.Image:
    """float32 ndarray [0, 1] -> PIL RGB image."""
    return Image.fromarray((canvas * 255).clip(0, 255).astype(np.uint8), mode="RGB")


def _extract_json(raw: str) -> str:
    """Extract the first JSON object from a raw model output string.

    The model may wrap its output in markdown code fences or add preamble text.

    Args:
        raw: Raw string from the model.

    Returns:
        Extracted JSON string.

    Raises:
        ValueError: If no valid JSON object is found.
    """
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON object found in model output: {raw!r}")
    return match.group(0)


def _parse_chunk(raw_output: str, horizon: int) -> ActionChunk | None:
    """Parse model output into an ActionChunk, returning None on error.

    Args:
        raw_output: Raw string generated by the model.
        horizon: Expected number of actions.

    Returns:
        Parsed ActionChunk, or None if parsing fails.
    """
    try:
        json_str = _extract_json(raw_output)
        data = json.loads(json_str)
        actions = [parse_action(a) for a in data["actions"]]
        return ActionChunk(actions=actions, horizon=horizon)
    except Exception as e:
        logger.warning("Failed to parse model output: %s", e)
        return None


class Predictor:
    """Wraps the loaded model and runs the chunk-execute-reobserve loop.

    Attributes:
        model: Loaded Qwen2.5-VL model.
        processor: Corresponding processor/tokenizer.
        horizon: Number of actions per chunk.
        max_chunks: Maximum inference iterations before stopping.
        ensemble_k: Number of actions to execute before re-observing.
    """

    def __init__(
        self,
        model: Any,
        processor: Any,
        horizon: int = 5,
        max_chunks: int = 20,
        ensemble_k: int = 5,
        max_parse_retries: int = 2,
    ) -> None:
        self.model = model
        self.processor = processor
        self.horizon = horizon
        self.max_chunks = max_chunks
        self.ensemble_k = min(ensemble_k, horizon)
        self.max_parse_retries = max_parse_retries

    @torch.inference_mode()  # type: ignore[misc]
    def _predict_chunk(
        self, canvas_pil: Image.Image, instruction: str, do_sample: bool = False
    ) -> ActionChunk | None:
        """Run one model forward pass and parse the output into an ActionChunk.

        Args:
            canvas_pil: Current canvas as a PIL image.
            instruction: Natural language editing instruction.
            do_sample: If True, use temperature sampling instead of greedy decoding.
                       Set to True on retries to escape deterministic bad generations.

        Returns:
            Parsed ActionChunk, or None if the output could not be parsed.
        """
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": instruction},
                ],
            }
        ]

        text = self.processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        inputs = self.processor(
            text=[text],
            images=[canvas_pil],
            return_tensors="pt",
        )
        inputs = {k: v.to(self.model.device) for k, v in inputs.items() if v is not None}

        output_ids = self.model.generate(
            **inputs,
            max_new_tokens=1024,
            do_sample=do_sample,
            temperature=0.3 if do_sample else None,
            top_p=0.9 if do_sample else None,
        )
        generated = output_ids[0][inputs["input_ids"].shape[1]:]
        raw_output = self.processor.decode(generated, skip_special_tokens=True)

        return _parse_chunk(raw_output, self.horizon)

    def run(
        self,
        image: Image.Image,
        instruction: str,
        show_preview: bool = False,
    ) -> tuple[Image.Image, list[ActionChunk]]:
        """Run the full chunk-execute-reobserve loop.

        Args:
            image: Input image to edit.
            instruction: Natural language instruction.
            show_preview: If True, open a live preview window. Closing the window
                          stops inference early.

        Returns:
            Tuple of (final edited image, list of all ActionChunks executed).
        """
        original = _image_to_float32(image)
        canvas = original.copy()
        executed_chunks: list[ActionChunk] = []
        parse_failures = 0

        fig = None
        im_handle = None
        if show_preview:
            import matplotlib.pyplot as plt

            plt.ion()
            fig, ax = plt.subplots(figsize=(8, 6))
            ax.axis("off")
            fig.canvas.manager.set_window_title("Elysium preview — close window to stop")
            im_handle = ax.imshow(image)
            plt.tight_layout()
            plt.show(block=False)
            plt.pause(0.001)

        for step in range(self.max_chunks):
            if show_preview and not plt.fignum_exists(fig.number):
                logger.info("Preview window closed — stopping inference")
                break

            canvas_pil = _float32_to_pil(canvas)
            chunk = self._predict_chunk(canvas_pil, instruction, do_sample=parse_failures > 0)

            if chunk is None:
                parse_failures += 1
                if parse_failures <= self.max_parse_retries:
                    logger.warning(
                        "Step %d: parse failure %d/%d, retrying with sampling",
                        step, parse_failures, self.max_parse_retries,
                    )
                    continue
                logger.warning(
                    "Step %d: exceeded max_parse_retries=%d, stopping",
                    step, self.max_parse_retries,
                )
                break

            parse_failures = 0

            if chunk.is_terminal:
                logger.info("Step %d: model signalled completion (all-noop chunk)", step)
                break

            if self.ensemble_k < self.horizon:
                partial_actions = chunk.actions[: self.ensemble_k]
                partial_chunk = ActionChunk(actions=partial_actions, horizon=self.ensemble_k)
                canvas = execute_chunk(canvas, partial_chunk, original=original)
            else:
                canvas = execute_chunk(canvas, chunk, original=original)

            executed_chunks.append(chunk)
            logger.info("Step %d: executed chunk (%d actions)", step, len(chunk.actions))

            if show_preview:
                im_handle.set_data(_float32_to_pil(canvas))
                fig.canvas.draw()
                fig.canvas.flush_events()
                plt.pause(0.001)
        else:
            logger.info("Reached max_chunks=%d, stopping", self.max_chunks)

        if show_preview:
            plt.ioff()
            plt.show(block=False)

        return _float32_to_pil(canvas), executed_chunks


def run_inference(
    image_path: Path,
    instruction: str,
    checkpoint_dir: Path,
    output_path: Path,
    config_path: Path = Path("configs/train.yaml"),
    show_preview: bool = False,
) -> None:
    """Load model from checkpoint and run inference on an image.

    Args:
        image_path: Path to the input image.
        instruction: Natural language instruction (e.g. "Draw a mustache on the face").
        checkpoint_dir: Path to the saved LoRA adapter or merged model directory.
        output_path: Path to save the resulting image.
        config_path: Path to train.yaml config.
        show_preview: If True, open a live preview window updated after each chunk.
    """
    try:
        from unsloth import FastVisionModel
    except ImportError as e:
        raise ImportError("Install unsloth: pip install unsloth") from e

    cfg = _load_config(config_path)
    infer_cfg = cfg.get("inference", {})
    horizon = cfg["data"]["action_horizon"]
    max_chunks = infer_cfg.get("max_chunks", 20)
    ensemble_k = infer_cfg.get("ensemble_execute_k", horizon)

    cached_repos = {r.repo_id for r in scan_cache_dir().repos}
    base_model = cfg["model"]["name"]
    local_only = base_model in cached_repos
    logger.info("Loading model from %s (local_files_only=%s)", checkpoint_dir, local_only)
    model, processor = FastVisionModel.from_pretrained(
        model_name=str(checkpoint_dir),
        load_in_4bit=cfg["model"].get("load_in_4bit", True),
        local_files_only=local_only,
    )
    FastVisionModel.for_inference(model)

    predictor = Predictor(
        model=model,
        processor=processor,
        horizon=horizon,
        max_chunks=max_chunks,
        ensemble_k=ensemble_k,
    )

    image = Image.open(image_path).convert("RGB")
    logger.info("Running inference: '%s'", instruction)

    result_image, chunks = predictor.run(image, instruction, show_preview=show_preview)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    result_image.save(str(output_path))
    logger.info("Saved result to %s (%d chunks executed)", output_path, len(chunks))


