tasks:
  sun:
    instruction: "draw a sun in top left corner"
    sessions:
      - white_512_20260422_000418
  sun_smiley:
    instruction: "draw a sun with smiley face in top left corner"
    sessions:
      - white_512_20260422_000922
  house:
    instruction: "draw a house with red roof, window and yellow door"
    sessions:
      - white_512_20260422_001353
  sky_ground:
    instruction: "draw green ground, sky and 2 clouds"
    sessions:
      - white_512_20260422_001925
  lightning_clouds:
    instruction: "draw 3 lightnings under the right cloud, the middle one big, two others smaller"
    sessions:
      - ground_sky_clouds_20260422_002920
  sunset_man_silhouette:
    instruction: "draw a small bush on right side of the horizon"
    sessions:
      - sunset_man_silhouette_20260426_204915
